In [2]:
import numpy as np
import pandas as pd
from IPython.display import display
import awoc
import random
import plotly.express as px

In [3]:
url_airport = 'https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat'
url_routers = 'https://raw.githubusercontent.com/jpatokal/openflights/master/data/routes.dat'

df_raw_airport = pd.read_csv(url_airport)
#display(df_raw_airport.head(3))
df_raw_routers = pd.read_csv(url_routers)
#display(df_raw_routers.head(3))

In [4]:
columns_airport = ['Airport ID', 'Name', 'City',
                   'Country', 'IATA', 'ICAO', 'Latitude', 'Longitude', 'Altitude', 'Timezone',
                   'DST', 'Tz database time zone', 'Type', 'Source']

columns_routers = ['Airline', 'Airline ID', 'Source airport', 'Source airport ID', 
                   'Destination airport', 'Destination airport ID', 'Codeshare', 'Stops', 'Equipment']

df_raw_airport = pd.read_csv(url_airport, names = columns_airport)
df_raw_routers = pd.read_csv(url_routers, names = columns_routers)

# Задание 1

Добавить столбец <code>Continent</code> с данными, которые будут содержать название континента.

In [5]:
world = awoc.AWOC()
def country_to_continent(country):
    try:
        continent = world.get_country_continent_name(country)
    except NameError:
        continent = np.nan
    
    return continent

In [6]:
df_airport = df_raw_airport.copy()
df_airport['Continent'] = df_airport['Country'].map(country_to_continent)
dict_country_error = {
    "Cote d'Ivoire": 'Ivory Coast',
    'Congo (Kinshasa)': 'Democratic Republic of the Congo',
    'Congo (Brazzaville)':'Republic of the Congo', 
    'Burma':'Myanmar',
    'Cocos (Keeling) Islands': 'Cocos Islands'}

dict_teritor_error = {
    'West Bank': 'Asia', 
    'Midway Islands': 'Oceania', 
    'French Guiana': 'South America', 
    'Martinique': 'North America',
    'Guadeloupe': 'North America', 
    'Virgin Islands': 'North America', 
    'Norfolk Island': 'Oceania', 
    'Johnston Atoll': 'Oceania',
    'Svalbard': 'Europe', 
    'Wake Island': 'Oceania'}

df_airport['Country'] = df_airport['Country'].replace(dict_country_error)
df_airport['Continent'] = df_airport['Country'].map(country_to_continent)
df_airport['Continent'] = df_airport['Continent'].fillna(df_airport['Country'].map(dict_teritor_error))
display(df_airport)

,Airport ID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,Tz database time zone,Type,Source,Continent
0,1,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,-6.081690,145.391998,5282,10,U,Pacific/Port_Moresby,airport,OurAirports,Oceania
1,2,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,-5.207080,145.789001,20,10,U,Pacific/Port_Moresby,airport,OurAirports,Oceania
2,3,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826790,144.296005,5388,10,U,Pacific/Port_Moresby,airport,OurAirports,Oceania
3,4,Nadzab Airport,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569803,146.725977,239,10,U,Pacific/Port_Moresby,airport,OurAirports,Oceania
4,5,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,AYPY,-9.443380,147.220001,146,10,U,Pacific/Port_Moresby,airport,OurAirports,Oceania
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7693,14106,Rogachyovo Air Base,Belaya,Russia,\N,ULDA,71.616699,52.478298,272,\N,\N,\N,airport,OurAirports,Europe
7694,14107,Ulan-Ude East Airport,Ulan Ude,Russia,\N,XIUW,51.849998,107.737999,1670,\N,\N,\N,airport,OurAirports,Europe
7695,14108,Krechevitsy Air Base,Novgorod,Russia,\N,ULLK,58.625000,31.385000,85,\N,\N,\N,airport,OurAirports,Europe
7696,14109,Desierto de Atacama Airport,Copiapo,Chile,CPO,SCAT,-27.261200,-70.779198,670,\N,\N,\N,airport,OurAirports,South America
7697,14110,Melitopol Air Base,Melitopol,Ukraine,\N,UKDM,46.880001,35.305000,0,\N,\N,\N,airport,OurAirports,Europe

# Задание 2

Из списка континентов случайно выбрать континент и срезать таблицу по названию континента и аэропорту имеющему код IATA (имеется в виду - для выбранного континента только аэропорты с кодом IATA). Каждый раз при выполнении кода континент случайно выбирается.

In [7]:
#Функция генерирует случайный континент из возможных 
def sluchainaya():
    sluchainaya = random.choice(df_airport["Continent"].unique())
    return(sluchainaya)

srez_airport = df_airport[df_airport["Continent"] == sluchainaya()]
srez_airport = srez_airport[srez_airport["IATA"] != "\\N"]
display(srez_airport)

,Airport ID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,Tz database time zone,Type,Source,Continent
205,207,Blida Airport,Blida,Algeria,QLD,DAAB,36.503601,2.814170,535,1,N,Africa/Algiers,airport,OurAirports,Africa
206,208,Bou Saada Airport,Bou Saada,Algeria,BUJ,DAAD,35.332500,4.206390,1506,1,N,Africa/Algiers,airport,OurAirports,Africa
207,209,Soummam Airport,Bejaja,Algeria,BJA,DAAE,36.712002,5.069920,20,1,N,Africa/Algiers,airport,OurAirports,Africa
208,210,Houari Boumediene Airport,Algier,Algeria,ALG,DAAG,36.691002,3.215410,82,1,N,Africa/Algiers,airport,OurAirports,Africa
209,211,Djanet Inedbirene Airport,Djanet,Algeria,DJG,DAAJ,24.292801,9.452440,3176,1,N,Africa/Algiers,airport,OurAirports,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7634,13714,"Paloich Airport, Heliport",Higleig,South Sudan,HGI,HSFA,10.529167,32.500556,1290,\N,\N,\N,airport,OurAirports,Africa
7650,13756,Arathusa Safari Lodge Airport,Arathusa,South Africa,ASS,FACC,-24.744165,31.522499,1200,2,U,\N,airport,OurAirports,Africa
7667,13808,Mchauru Airport,Geita,Tanzania,GIT,HTRU,-2.813667,32.172472,3955,3,N,\N,airport,OurAirports,Africa
7668,13821,Gitega Airport,Gitega,Burundi,GID,HBBE,-3.417209,29.911308,5741,2,U,\N,airport,OurAirports,Africa
7682,14095,Songwe Airport,Mbeya,Tanzania,MBI,HTGW,-8.919942,33.273981,4412,\N,\N,\N,airport,OurAirports,Africa

# Задание 3

На основе таблицы связи аэропортов создать таблицу с кодом аэропорта, количеством взлетов и количеством посадок.

In [8]:
#Задание 3 
vzlet = df_raw_routers.groupby('Source airport').count()["Source airport ID"]
posad = df_raw_routers.groupby('Destination airport').count()["Destination airport ID"]
#вроде нормальный вариант
gotovo2 = pd.concat([vzlet, posad], axis=1)
gotovo2.rename(columns = {"Source airport ID" : 'vzlet' ,"Destination airport ID" : 'posad' }, inplace=True)
#заполняю \N нулями, но вряд ли это правильно
#для того, чтобы вычислить кол-во взлетов и посадок, нужно числовое значение
#но в целом мне кажется это некорректным, однако, не знаю, как сделать иначе
gotovo2 = gotovo2.fillna(0)
gotovo2 = gotovo2.astype(int)
display(gotovo2)



#вариант через Владивосток :) 
#vzlet.name ='vzlet'
#posad.name ='posad'
#rrr = pd.DataFrame(np.union1d(df_raw_routers["Source airport ID"].unique(),df_raw_routers["Destination airport ID"].unique()))
#rrr.rename(columns = {0 : 'Airport ID'}, inplace=True)
#gotovo1 = pd.merge(pd.DataFrame(vzlet).merge(rrr['Airport ID'], 
 #                   left_index=True, 
  #                  right_on = 'Airport ID').reset_index(drop=True)[['Airport ID','vzlet']], 
   #      pd.DataFrame(posad).merge(rrr['Airport ID'], 
    #                left_index=True, 
     #               right_on = 'Airport ID').reset_index(drop=True)[['Airport ID','posad']], 
      #   how='outer')
#display(gotovo1)

     vzlet  posad
AAE      9      9
AAL     20     21
AAN      2      2
AAQ      3      3
AAR      8      8
..     ...    ...
ORX      0      3
QFX      0      1
SPI      0      5
TUA      0      1
UII      0      1

[3425 rows x 2 columns]

# Задание 4

Используя в качестве ключа код аэропорта слить данные для отобранного континента и собрать таблицу - страна, название аэропорта, количество взлет/посадок (сумма взлетов и посадок)

In [12]:
gotovo3 = gotovo2.copy()
gotovo3["vzletposad"] = gotovo3["vzlet"] + gotovo3["posad"] 
gotovo3["IATA"] = gotovo3.index
gotovo3 = gotovo3[["IATA", "vzletposad"]]
gotovo3 = gotovo3[gotovo3["IATA"] != "\\N"]
display(gotovo3)

    IATA  vzletposad
AAE  AAE          18
AAL  AAL          41
AAN  AAN           4
AAQ  AAQ           6
AAR  AAR          16
..   ...         ...
ORX  ORX           3
QFX  QFX           1
SPI  SPI           5
TUA  TUA           1
UII  UII           1

[3425 rows x 2 columns]

In [13]:
srez_airport = df_airport[df_airport["Continent"] == sluchainaya()]
srez_airport = srez_airport[["IATA", "Name", "Country"]]
#display(srez_airport)
merged = pd.merge(srez_airport, gotovo3, on="IATA", how="left")
merged["vzletposad"] = merged["vzletposad"].fillna(0)
merged["vzletposad"] = merged["vzletposad"].astype(int)
display(merged[merged["IATA"] != "\\N"])

,IATA,Name,Country,vzletposad
0,GKA,Goroka Airport,Papua New Guinea,10
1,MAG,Madang Airport,Papua New Guinea,16
2,HGU,Mount Hagen Kagamuga Airport,Papua New Guinea,22
3,LAE,Nadzab Airport,Papua New Guinea,22
4,POM,Port Moresby Jacksons International Airport,Papua New Guinea,102
...,...,...,...,...
612,RRR,Raroia Airport,French Polynesia,0
613,KHZ,Kauehi Airport,French Polynesia,2
614,TKV,Tatakoto Airport,French Polynesia,0
615,TDS,Sasereme Airport,Papua New Guinea,0
618,NKB,Noonkanbah Airport,Australia,0

# Задание 5

1. Найти коды аэропортов для которых нет взлет/посадок в таблице аэропортов.
2. Найти коды аэропортов для которых нет названий в таблице связей аэропортов.

In [14]:
#найти коды аэропортов для которых нет взлет/посадок в таблице аэропортов
display(np.setdiff1d(df_raw_airport[df_raw_airport["IATA"] != "\\N"]["IATA"].unique(), 
                     np.union1d(df_raw_routers["Destination airport"].unique(),  df_raw_routers["Source airport"].unique())))
#найти коды аэропортов для которых нет названий в таблице связей аэропортов
display(np.setdiff1d(np.union1d(df_raw_routers["Destination airport"].unique(),  df_raw_routers["Source airport"].unique()), 
                     df_raw_airport[df_raw_airport["IATA"] != "\\N"]["IATA"].unique()))

array(['AAA', 'AAC', 'AAF', ..., 'ZXT', 'ZZU', 'ZZV'], dtype=object)

array(['ACU', 'AGM', 'AOQ', 'AOS', 'ATT', 'BCV', 'BFQ', 'BLD', 'BNY',
       'BSS', 'BVV', 'CBS', 'CGA', 'CKD', 'CKX', 'CUK', 'CXF', 'CZH',
       'CZJ', 'DGA', 'DHB', 'DIW', 'EAR', 'EDA', 'ELL', 'EXI', 'FBS',
       'FDE', 'FSZ', 'FVM', 'GCW', 'GHE', 'GLN', 'GNU', 'GRV', 'GSM',
       'HKB', 'HYL', 'IGM', 'IKE', 'INB', 'INC', 'IOQ', 'IOT', 'IUI',
       'JJA', 'JUK', 'JUU', 'KAE', 'KBC', 'KBU', 'KCC', 'KCG', 'KCL',
       'KCQ', 'KGQ', 'KGX', 'KHQ', 'KKB', 'KKI', 'KLL', 'KOZ', 'KPB',
       'KPR', 'KTB', 'KUS', 'KUZ', 'KWF', 'KXU', 'KZB', 'LBP', 'LCR',
       'LGQ', 'LKE', 'LMC', 'LNV', 'LSA', 'MCM', 'MJU', 'MLH', 'MNT',
       'MPP', 'MRA', 'MTE', 'NIQ', 'NKI', 'NSQ', 'NTG', 'NUP', 'OGM',
       'OHH', 'OLH', 'ORI', 'ORZ', 'OTD', 'PAF', 'PEC', 'PHO', 'PLJ',
       'PND', 'PPV', 'PQS', 'PUM', 'PVE', 'PYC', 'QFN', 'QFX', 'QJH',
       'QOQ', 'QUB', 'QUV', 'QUW', 'RCE', 'RDV', 'RIG', 'RKA', 'RMP',
       'SAE', 'SAX', 'SGG', 'SHC', 'SIC', 'SLI', 'SQS', 'SRK', 'SRV',
       'SSB', 'SVC', 'SVK', 'SVR', 'SVS', 'SXP', 'SYB', 'SZE', 'SZI',
       'TAL', 'TCD', 'TCR', 'TCT', 'TFI', 'TGC', 'THD', 'TKE', 'TLT',
       'TNK', 'TNO', 'TQA', 'TQI', 'TVS', 'TZA', 'UGB', 'UPK', 'WBB',
       'WNH', 'WSX', 'WTL', 'WWP', 'WWT', 'XEQ', 'YKT', 'ZBL', 'ZDY',
       'ZEL'], dtype=object)

# Задание 6

Для таблицы в задании 4, для трех крупнейших аэропортов для каждой страны, собрать ряд - первый индекс: название страны, второй индекс: название аэропорта, значение: количество взлет посадок. Первый индекс упорядочен по названию страны (по алфавиту), а назание аэропорта по количеству взлет посадок от большего к меньшему.

In [21]:
merged2 = merged.copy()
merged2 = merged2[merged2["IATA"] != "\\N"]
merged2 = merged2.pivot_table(values="vzletposad", index=["Country", "Name"])
#merged2 = merged2.groupby("Country")
#merged2 = merged2.apply(lambda row: row.nlargest(3, "vzletposad"))
#merged2 = merged2.set_index(["Country", "Name"])
#merged2 = merged2.drop(columns=['IATA'])
display(merged2)

                                                   vzletposad
Country           Name
American Samoa    Fitiuta Airport                           0
                  Pago Pago International Airport           2
Australia         Adelaide International Airport          102
                  Albany Airport                            6
                  Albury Airport                            8
...                                                       ...
Vanuatu           Valesdir Airport                          2
                  Walaha Airport                            2
Wake Island       Wake Island Airfield                      0
Wallis and Futuna Hihifo Airport                            6
                  Pointe Vele Airport                       2

[556 rows x 1 columns]

# Задание 7

Для каждого континента отобрать не более 3 стран с наибольшим количеством взлет посадок и нанести их на географическую карту.

In [12]:
merged3 = merged.copy()
merged3 = merged3[merged3["IATA"] != "\\N"]
merged3 = merged3.groupby("Country").sum()["vzletposad"]
display(merged3.nlargest(3))

Country
Brazil       2793
Colombia      714
Argentina     511
Name: vzletposad, dtype: int32

# Задание 8

Для каждого континента отобрать 5 наиболее крупных аэропортов с наибольшим количеством взлет посадок и нанести их на географическую карту.

In [13]:
merged4 = merged.copy()
merged4 = merged4[merged4["IATA"] != "\\N"]
merged4 = merged4.groupby(["Country","Name"]).sum()
display(merged4["vzletposad"].nlargest(5))

Country   Name
Brazil    Guarulhos - Governador André Franco Montoro International Airport    387
Colombia  El Dorado International Airport                                      307
Peru      Jorge Chávez International Airport                                   230
Brazil    Presidente Juscelino Kubistschek International Airport               197
          Rio Galeão – Tom Jobim International Airport                         194
Name: vzletposad, dtype: int32

# Задание 9

Для наиболее крупных аэропортов (задание 8) построить маршрутную транспортную сеть и нанести их на географическую карту, линия должна отображать интенсивность взаимосвязи (прозрачность, толщина).

In [14]:
#нервных клеток больше не осталось...